- name: Copiar archivo
  become: true
  copy:
    path: 
     src: /Escritorio/demo_carpeta/archivo_vacio.txt 
        dest: /home/  
        mode: '0644'  

- name: Verificar si el archivo existe
  stat:
    path: /home/archivo_vacio.txt
     register: existe el archivo        